enum Events {
    EVT_PUZZLE_REMOVE_CELL = 'EVT_PUZZLE_REMOVE_CELL',
    EVT_PUZZLE_GAME_OVER = 'EVT_PUZZLE_GAME_OVER',
    EVT_DIAMOND_TIMEOUT = 'EVT_DIAMOND_TIMEOUT',
    EVT_DIAMOND_START_WARNING = 'EVT_DIAMOND_START_WARNING',
    EVT_DIAMOND_STOP_WARNING = 'EVT_DIAMOND_STOP_WARNING',
    EVT_DIAMOND_DISPEL_FINISHED = 'EVT_DIAMOND_DISPEL_FINISHED',
    EVT_DIAMOND_REVIVE_GIVEUP = 'EVT_DIAMOND_REVIVE_GIVEUP',
    EVT_DIAMOND_USE_TIME = 'EVT_DIAMOND_USE_TIME',
    EVT_DIAMOND_SHOW_TURNPLATE = 'EVT_DIAMOND_SHOW_TURNPLATE',
    EVT_DIAMOND_FOCUS_DESTROY = 'EVT_DIAMOND_FOCUS_DESTROY',
    EVT_DIAMOND_CLOSE_REWARDVIEW = 'EVT_DIAMOND_CLOSE_REWARDVIEW',

    EVT_FINISED_SHARE = 'EVT_FINISED_SHARE',
    EVT_ATTR_CHANGE = 'EVT_ATTR_CHANGE',
}

export = Events